### ISSUE TITLE
post alert failed

### ISSUE THREAD

**Issue by willhope** [alerta/zabbix-alerta#14]
2017-03-28 21:58:03.126 root[28378] MainThread INFO - [alerta] endpoint=http://200.200.114.161/api key=demo000000
2017-03-28 21:58:03.129 root[28378] MainThread ERROR - __init__() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zabbix_alerta.py", line 223, in main
    alert = parse_zabbix(args.summary, args.body)
  File "/usr/lib/zabbix/alertscripts/zabbix_alerta.py", line 152, in parse_zabbix
    return Alert(**alert)
TypeError: __init__() takes exactly 3 arguments (2 given)
2017-03-28 21:59:03.263 root[28793] MainThread INFO - [alerta] endpoint=http://200.200.114.161/api key=demo000000
2017-03-28 21:59:03.266 root[28793] MainThread ERROR - __init__() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zabbix_alerta.py", line 223, in main
    alert = parse_zabbix(args.summary, args.body)
  File "/usr/lib/zabbix/alertscripts/zabbix_alerta.py", line 152, in parse_zabbix
    return Alert(**alert)
TypeError: __init__() takes exactly 3 arguments (2 given)

**Comment by satterly** [comment]
Did you follow the Install and Configuration sections in the [README](https://github.com/alerta/zabbix-alerta#installation)?

What's the output of `pip list` ?

**Comment by willhope** [comment]
alerta (4.8.8)
ansible (2.0.2.0)
Babel (1.3)
backports.ssl-match-hostname (3.4.0.2)
blinker (1.4)
chardet (2.2.1)
colorama (0.3.7)
colorlog (2.6.0)
configobj (4.7.2)
debtcollector (0.3.1.dev6)
decorator (3.4.0)
Django (1.8.3)
ecdsa (0.13)
futures (3.0.5)
httplib2 (0.7.7)
iniparse (0.4)
iotop (0.6)
IPy (0.75)
iso8601 (0.1.11)
Jinja2 (2.7.2)
keyring (5.0)
kitchen (1.1.1)
M2Crypto (0.21.1)
MarkupSafe (0.11)
msgpack-python (0.4.7)
MySQL-python (1.2.3)
netaddr (0.7.12)
netifaces (0.10.4)
oslo.config (1.9.4.dev8)
oslo.i18n (1.5.1.dev7)
oslo.serialization (1.4.1.dev4)
oslo.utils (1.4.1.dev7)
paramiko (1.15.1)
pbr (1.8.1)
pip (7.1.0)
policycoreutils-default-encoding (0.1)
prettytable (0.7.2)
pyasn1 (0.1.6)
pycrypto (2.6.1)
pycurl (7.19.0)
pygobject (3.8.2)
pygpgme (0.3)
pyliblzma (0.5.3)
pyparsing (2.0.3)
python-gflags (2.0)
python-keyczar (0.71rc0)
python-keystoneclient (1.3.3.dev32)
python-novaclient (2.23.3.dev48)
python-sfprocessclient (1.0.0)
pytz (2012d)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.11)
pyzmq (14.3.1)
requests (2.7.0)
rsa (3.4.1)
salt (2016.11.2)
seobject (0.1)
sepolicy (1.1)
setuptools (0.9.8)
simplejson (3.3.3)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
stevedore (1.3.1.dev5)
tornado (4.2.1)
urlgrabber (3.10)
urllib3 (1.10.2)
WebOb (1.2.3)
wrapt (1.10.4)
yum-metadata-parser (1.1.4)
zabbix-alerta (3.2.0)

alerta (4.8.8) zabbix-alerta (3.2.0) has installed

**Comment by willhope** [comment]
when i use alerta client with python command, it aslo go something wrong. like this:
>>> api.send(alert)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "alertaclient/api.py", line 65, in send
    return self.send_alert(msg)
  File "alertaclient/api.py", line 58, in send_alert
    return self._post('/alert', data=str(alert))
  File "alertaclient/api.py", line 205, in _post
    return response.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 819, in json
    encoding = self.encoding
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by willhope** [comment]
debug info is
2017-03-29 11:34:47,878 - alertaclient.api - DEBUG - Request Headers: {'Content-Length': '403', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.13.0', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Authorization': 'Key '}
2017-03-29 11:34:47,879 - alertaclient.api - DEBUG - Request Body: {"status": "unknown", "origin": "/xyclouds.com", "resource": "net01", "severity": "normal", "correlate": [], "tags": [], "text": "", "createTime": "2017-03-29T03:29:46.581Z", "value": "n/a", "event": "down", "environment": "Code", "customer": null, "service": [], "rawData": "", "timeout": 86400, "attributes": {}, "group": "Misc", "type": "exceptionAlert", "id": "05760c52-a79a-4e22-b856-947798dc2144"}
2017-03-29 11:34:47,879 - alertaclient.api - DEBUG - Response Headers: {'Content-Length': '201', 'Expires': '0', 'Content-Type': 'text/html', 'Cache-control': 'private'}
2017-03-29 11:34:47,879 - alertaclient.api - DEBUG - Response Body: Sorry, Page Not Found

**Comment by willhope** [comment]
when use alerta client with python command, generate alert show include 'services' value, like this:
alert = Alert(resource='net01', event='down', environment='Code', service=["Network"])

**Comment by willhope** [comment]
i configure my zabbix again, then everything is ok

**Comment by satterly** [comment]
great. good work. thanks for letting me know.
