### ISSUE TITLE
No /var/log/zabbix in alpine linux

### ISSUE THREAD

**Issue by satterly** [alerta/zabbix-alerta#16]
```
bash-4.3# zabbix-alerta http://alerta/api "foo" "bar"
Traceback (most recent call last):
  File "/usr/bin/zabbix-alerta", line 9, in <module>
    load_entry_point('zabbix-alerta==3.2.0', 'console_scripts', 'zabbix-alerta')()
  File "/usr/lib/python2.7/site-packages/zabbix_alerta.py", line 216, in main
    LOG.basicConfig(filename=LOG_FILE, format=LOG_FORMAT, datefmt=LOG_DATE_FMT, level=LOG.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/zabbix/zabbix_alerta.log'
```

**Comment by satterly** [comment]
Fixed by fb3b286dc477742603387e67dc569028b1e004f4
