### ISSUE TITLE
MainThread ERROR - Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by tiago-cruz-movile** [alerta/zabbix-alerta#24]
CentOS 7, Python 2.7, Zabbix 3.4:

- /var/log/zabbix/zabbix_alerta.log:

```
2018-08-09 21:46:50.159 root[19423] MainThread INFO - [alerta] endpoint=https://alerta.it.xxx.com/ key=
2018-08-09 21:46:50.207 root[19423] MainThread ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 68, in send_alert
    r = self.http.post('/alert', data)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 350, in post
    return self._handle_error(response)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 373, in _handle_error
    resp = response.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

- with key:

```
2018-08-10 18:02:40.367 root[9435] MainThread INFO - [alerta] endpoint=https://alerta.it.xxx.com key=adadasdasdasd-CnWR6Qu
2018-08-10 18:02:40.408 root[9435] MainThread ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 68, in send_alert
    r = self.http.post('/alert', data)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 350, in post
    return self._handle_error(response)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 373, in _handle_error
    resp = response.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

- webserver:

```
ip=\10.111.83.71 [\10/Aug/2018:17:42:27 +0000] "\POST /alert HTTP/1.0" \404 \169 "\-" "\python-requests/2.19.1"```

**Comment by tiago-cruz-movile** [comment]
Changing the uri 
- from `http://ip:8080`
- to `http://ip:8080/api` worked.

I suggest you to update the readme :)
note: using the docker-compose

**Comment by satterly** [comment]
Done 👍
