### ISSUE TITLE
 ERROR - 'ok' is not a valid severity

### ISSUE THREAD

**Issue by kssanthosh** [alerta/zabbix-alerta#27]
I'm getting below error on the zabbix_alerta.log.

```
 MainThread ERROR - 'ok' is not a valid severity
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
  File "/usr/local/lib/python2.7/dist-packages/alertaclient/api.py", line 68, in send_alert
    r = self.http.post('/alert', data)
  File "/usr/local/lib/python2.7/dist-packages/alertaclient/api.py", line 378, in post
    return self._handle_error(response)
  File "/usr/local/lib/python2.7/dist-packages/alertaclient/api.py", line 406, in _handle_error
    raise UnknownError(resp['message'])
UnknownError: 'ok' is not a valid severity
```

Is it possible to for anyone to help me on this?

**Comment by kssanthosh** [comment]
I have resolved the issue could see issue is due to the deceleration on the alerta server on alerta.conf
