### ISSUE TITLE
Zabbix on Centos 7 Python 2

### ISSUE THREAD

**Issue by marcodesantis71** [alerta/zabbix-alerta#28]
Hi All,

I have installed Newest version of Alerta on Ubuntu 16. I integrated Nagios on Alerta.

Now I try to send alarm to Alerta API Server with python 3.

But on my Centos 7 I have Python 2.

On log of Zabbix_server I found:

Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zabbix-alerta", line 9, in <module>
    load_entry_point('zabbix-alerta==3.5.0', 'console_scripts', 'zabbix-alerta')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/zabbix_alerta.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/alerta-6.5.0-py2.7.egg/alertaclient/__init__.py", line 26, in <module>
    """)
ImportError: You are running Alerta 6.0 on Python 2

Alerta 6.0 and above are no longer compatible with Python 2.

Make sure you have pip >= 9.0 to avoid this kind  of issue,
as well as setuptools >= 24.2:

 $ pip install pip setuptools --upgrade

Your choices:

- Upgrade to Python 3.

- Install an older version of Alerta:

 $ pip install 'alerta<6.0'

See the following URL for more up-to-date information:

https://github.com/alerta/alerta/wiki/Python-3

How can I resolve this error?

Thanks.

**Comment by satterly** [comment]
What have you tried from the list of options in that error message?

**Comment by marcodesantis71** [comment]
HI,

on centos 7 I installe python3.6 on virtual env. And I can use python3 with:

python36 -m venv alerta

But on Zabbix, alerta script to forward problem su Alerta API Server use python 2.

Is there a command to invoke python virtualenv from Zabbix alerta script?

**Comment by satterly** [comment]
You need to install the `zabbix-alerta` script using the version of `python` or `pip` installed by the virtualenv. ie. `/your/python3/virtualenv/bin/python setup.py install` or `/your/python3/virtualenv/bin/pip install git+https://github.com/alerta/zabbix-alerta`

**Comment by marcodesantis71** [comment]
OK. Thanks.

I try.

**Comment by satterly** [comment]
Did you get this to work?
