### ISSUE TITLE
Alerta V7 + Zabbix getting read time out when trying to close ticket

### ISSUE THREAD

**Issue by gabricar** [alerta/zabbix-alerta#36]
Some of my tickets are not getting closed on alerta. Looking at the zabbix_alerta.log I can see a read timeout error message. I don't see any issues on the alerta server that may cause this timeout. Plus I have an alerta v5 running in parallel and the same alert gets closed there. this is happening very randomly. Is it possible to increase this timeout?

2020-02-21 01:04:27.884 root[5918] MainThread ERROR - HTTPConnectionPool(host='10.3.30.6', port=80): Read timed out. (read timeout=5.0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 68, in send_alert
    r = self.http.post('/alert', data)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 330, in post
    response = self.session.post(url, data=json.dumps(data, cls=CustomJsonEncoder), headers=headers, auth=self.auth, timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='10.3.30.6', port=80): Read timed out. (read timeout=5.0)

**Comment by satterly** [comment]
Yes, we just need to add the option to this line ...

https://github.com/alerta/zabbix-alerta/blob/b8f552fcbf195c2032e9fbd6a59dd04f7178d94f/zabbix_alerta.py#L217

**Comment by satterly** [comment]
You can now add `timeout` as an option in the configuration file.
