### ISSUE TITLE
Zabbix Alerta v7-  trigger does not allow manual closing.

### ISSUE THREAD

**Issue by gabricar** [alerta/zabbix-alerta#37]
Zabbix 4.0 cannot close some alerts on Alerta v7. I can see the error message ", Cannot close problem: trigger does not allow manual closing." But the alert is still open on Alerta. If I try to close it manually on the Alerta GUI it shows a similar exception error message on my browser.

('Zabbix: ERROR - %s', ZabbixAPIException('Error -32500: Application error., Cannot close problem: trigger does not allow manual closing.', -32500)) (500)

2020-02-22 01:05:16.177 root[10257] MainThread ERROR - ('Zabbix: ERROR - %s', ZabbixAPIException('Error -32500: Application error., Cannot close problem: trigger does not allow manual closing.', -32500))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zabbix_alerta.py", line 222, in main
    api.send_alert(**alert)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 68, in send_alert
    r = self.http.post('/alert', data)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 378, in post
    return self._handle_error(response)
  File "/usr/lib/python2.7/site-packages/alertaclient/api.py", line 406, in _handle_error
    raise UnknownError(resp['message'])
UnknownError: ('Zabbix: ERROR - %s', ZabbixAPIException('Error -32500: Application error., Cannot close problem: trigger does not allow manual closing.', -32500))

**Comment by gabricar** [comment]
The same alert is being closed normally on alerta v5.

**Comment by satterly** [comment]
Closing. Stale issue.
