### ISSUE TITLE
Problem on post alert

### ISSUE THREAD

**Issue by jehster** [alerta/zabbix-alerta#4]
Hi,

I've configured my zabbix to post alert to Alerta. An alerta should have been raised but I got this error on alerta server. I imagine that something is not welle configured but don't know what.

```
10.1.3.155 - - [25/Aug/2015 13:27:59] "POST //alert HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1439, in raise_routing_exception
    raise FormDataRoutingRedirect(request)
FormDataRoutingRedirect: A request was sent to this URL (http://alert/) but a redirect was issued automatically by the routing system to "http://alert/".  Make sure to directly send your POST-request to this URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.
```

Note: this exception is only raised in debug mode

```
10.1.2.206 - - [25/Aug/2015 13:27:59] "GET /alerts/count?status=closed HTTP/1.1" 200 -
```

**Comment by satterly** [comment]
This line doesn't look right...

```
10.1.3.155 - - [25/Aug/2015 13:27:59] "POST //alert HTTP/1.1" 500 -
```

There is an extra forward slash. It should look like this...

```
127.0.0.1 - - [26/Aug/2015 12:43:28] "POST /alert HTTP/1.1" 201 -
```

In step 2, when you add the alerta API endpoint URL have you added an extra slash?

```
2/ Modify the Media for the Admin user [Administration > Users]

Type: alerta
Send to: http://x.x.x.x:8080         <--- API hostname/IP and port of alerta server
When active: 1-7,00:00-24:00
Use if severity: (all)
Status: Enabled
```

ie. does it look like the above, or like this?

```
Send to: http://x.x.x.x:8080/
```

**Comment by jehster** [comment]
One again, you're right. I've changed the media and everything is ok.
I know I should not ask this here but a init script to start alertad on server boot ? 

I did not find any in source code of alertad.

**Comment by satterly** [comment]
Alerta is designed to run as a WSGI application behind Apache or nginx and that's the only way I've ever run it in production environments.

There are quite a few examples of how to run it as a WSGI app behind a web server (or using gunicorn) [here](https://github.com/alerta/vagrant-try-alerta/blob/master/scripts/alerta.sh), [here](https://github.com/alerta/alerta-cfn/blob/master/Alerta_Single_Instance.template), [here](https://github.com/alerta/openshift-api-alerta/blob/master/wsgi.py), and [here](https://github.com/alerta/docker-alerta/blob/master/supervisord.conf).

I only run `alertad` as stand-alone process during development.
